# Generated by Django 5.0.6 on 2024-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0002_employer_confirm_alter_employer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=100)),
                ('highqua', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('passworde', models.CharField(max_length=10)),
                ('con', models.CharField(max_length=10)),
            ],
        ),
    ]
