# Generated by Django 5.0.6 on 2024-06-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phonenumber',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='code',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=4, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='phonenumber',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='pin',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
