# Generated by Django 5.0.6 on 2024-06-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0006_postajob_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='jobdes',
            field=models.CharField(max_length=500),
        ),
    ]
