# Generated by Django 5.0.6 on 2024-06-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0009_alter_employer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='place',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='passworde',
            new_name='password',
        ),
    ]
