# Generated by Django 5.0.6 on 2024-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0010_rename_place_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postajob',
            name='company',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
