# Generated by Django 5.0.6 on 2024-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0012_postajob_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='jobdes',
            field=models.CharField(max_length=3000),
        ),
    ]
