# Generated by Django 5.0.6 on 2024-06-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0013_alter_postajob_jobdes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postajob',
            old_name='area',
            new_name='state',
        ),
    ]
