# Generated by Django 5.0.6 on 2024-06-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0014_rename_area_postajob_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postajob',
            name='address',
        ),
    ]
