# Generated by Django 5.0.6 on 2024-06-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0015_remove_postajob_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userid', models.IntegerField()),
                ('jobid', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
