# Generated by Django 5.0.6 on 2024-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0016_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='jobid',
            field=models.CharField(max_length=50),
        ),
    ]
