# Generated by Django 5.0.6 on 2024-06-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0019_alter_apply_jobid_alter_apply_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobport.employee'),
            preserve_default=False,
        ),
    ]
