# Generated by Django 5.0.6 on 2024-06-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0020_apply_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(default=0, upload_to='resume'),
            preserve_default=False,
        ),
    ]
