# Generated by Django 5.0.6 on 2024-06-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0021_employee_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=0, upload_to='p'),
            preserve_default=False,
        ),
    ]
