# Generated by Django 5.0.6 on 2024-07-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0023_remove_apply_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
