# Generated by Django 5.0.6 on 2024-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0024_rename_first_name_employee_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
