# Generated by Django 5.0.6 on 2024-07-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0025_apply_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='sus',
            field=models.BooleanField(default=True),
        ),
    ]
