# Generated by Django 5.0.6 on 2024-07-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0026_employee_sus_employer_sus'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
