# Generated by Django 5.0.6 on 2024-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobport', '0028_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
